name: Code Quality Checks

on:
  push:
    branches: ['**'] # Run on all branches
  pull_request:
    branches: [main] # Run on PRs targeting main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm i

      - name: Run linting
        run: pnpm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: init project
        run: pnpm run init

      - name: Install dependencies
        run: pnpm i

      - name: Run tests
        run: pnpm run ci
